server:
  port: 8888
  application:
    name: sec

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sbtest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:
      content-type: text/html
